# Generated by Django 6.0 on 2026-01-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(help_text='Image for the category card', upload_to='category_images/')),
                ('description', models.TextField(help_text='A short article about this category.')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Image of the pet', upload_to='pet_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Is this pet available for adoption?')),
                ('species', models.CharField(help_text='e.g., Golden Retriever, Siamese', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('habitual_status', models.TextField(blank=True, help_text="Describe the pet's habits")),
                ('foods', models.TextField(blank=True, help_text="Describe the pet's diet")),
                ('vaccination', models.TextField(blank=True, help_text='Vaccination status and history')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petapp.category')),
            ],
        ),
    ]
