# Generated by Django 6.0 on 2026-01-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='average_lifespan',
        ),
    ]
