# Generated by Django 6.0 on 2026-01-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_adoptionapplication_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='admin_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
