# Generated by Django 6.0.6 on 2026-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_adoptionapplication_admin_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_id',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
