# Generated by Django 6.0.6 on 2026-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_aboutfeature_service_sitesetting_whychooseusitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseusitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon text', max_length=50),
        ),
    ]
