# Generated by Django 6.0.6 on 2026-06-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_whychooseusitem_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for cards')),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Additional Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_name', models.CharField(blank=True, help_text='Adopted pet name', max_length=100)),
                ('content', models.TextField(help_text='Testimonial text')),
                ('image', models.ImageField(blank=True, help_text='Photo of the person or pet', upload_to='testimonials/')),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(db_index=True, help_text='e.g., Golden Retriever, Siamese', max_length=100),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['status'], name='petapp_adop_status_1bd89b_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['email'], name='petapp_adop_email_7433fc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email'], name='petapp_cont_email_47c08e_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['is_available'], name='petapp_pet_is_avai_79c946_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['category', 'is_available'], name='petapp_pet_categor_0e6c26_idx'),
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='petapp.pet'),
        ),
    ]
