# Generated by Django 6.0.6 on 2026-06-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_blogpost_faq_petimage_testimonial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
