# Generated by Django 6.0.6 on 2026-06-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0009_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_svg', models.TextField(blank=True, help_text='SVG markup for the icon')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('navbar', 'Navbar'), ('footer', 'Footer')], default='navbar', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url_name', models.CharField(blank=True, help_text="Django URL name (e.g. 'home', 'about')", max_length=200)),
                ('url_external', models.URLField(blank=True, help_text='External URL (overrides url_name if set)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='petapp.navigationlink')),
            ],
            options={
                'ordering': ['placement', 'order'],
            },
        ),
    ]
